# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 23:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20160310_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2016, 3, 10, 23, 25, 42, 274920, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
